# Compiler and Flags
CXX = afl-clang-lto++
CXX = afl-clang++
CXX = afl-clang-fast++
CXXFLAGS = -std=c++20 -O2
AFL_FLAGS = AFL_SKIP_CPUFREQ=1

TARGET = fuzz_harness
SEED_DIR = $(CURDIR)/afl/seed
OUTPUT_DIR = $(CURDIR)/afl/output

# Source and Headers
INC = -Isrc/ -Ideps/cnl/include
FUZZ_SRCS = src/apps/main.cpp src/*.cpp

$(TARGET):
	$(CXX) $(CXXFLAGS) $(INC) $(FUZZ_SRCS) -o $(TARGET)

run:
	mkdir -p $(SEED_DIR)
	cp docs/given_example.csv $(SEED_DIR)
	mkdir -p $(OUTPUT_DIR)
	#AFL_SKIP_CPUFREQ=1 afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) ./$(TARGET)

	# Core 1: Primary Node
	$(AFL_FLAGS) afl-fuzz -m none -i $(SEED_DIR) -o $(OUTPUT_DIR) -M master -- ./$(TARGET) @@ &

	# And 7 slaves
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_1 -- ./$(TARGET) @@ > /dev/null 2>&1 &
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_2 -- ./$(TARGET) @@ > /dev/null 2>&1 &
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_3 -- ./$(TARGET) @@ > /dev/null 2>&1 &
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_4 -- ./$(TARGET) @@ > /dev/null 2>&1 &
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_5 -- ./$(TARGET) @@ > /dev/null 2>&1 &
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_6 -- ./$(TARGET) @@ > /dev/null 2>&1 &
	$(AFL_FLAGS) afl-fuzz -i $(SEED_DIR) -o $(OUTPUT_DIR) -S slave_7 -- ./$(TARGET) @@ > /dev/null 2>&1 &

stop:
	@echo "Stopping all afl-fuzz processes..."
	-pkill -f "afl-fuzz"

status:
	afl-whatsup $(OUTPUT_DIR)

clean:
	rm -f $(TARGET)

.PHONY: all run clean

