#pragma once

#include "accumulation_distribution_line.hpp"
#include "aggressive_volume_drift.hpp"
#include "aggressive_volume_weight_drift.hpp"
#include "block_trade_detector.hpp"
#include "buy_sell_lot_ratio.hpp"
#include "chaikin_oscillator.hpp"
#include "cumulative_volume_delta.hpp"
#include "cumulative_vwap.hpp"
#include "ease_of_movement.hpp"
#include "ema_signal.hpp"
#include "flash_sweep_footprint.hpp"
#include "last_trade_price.hpp"
#include "macd_signal.hpp"
#include "money_flow_index.hpp"
#include "on_balance_volume.hpp"
#include "rsi_signal.hpp"
#include "tick_ltp_delta.hpp"
#include "tick_run_length.hpp"
#include "trade_size_depth_ratio.hpp"
#include "trade_size_zscore.hpp"
#include "volume_price_trend.hpp"
#include "volumetric_price_target_distance.hpp"
#include "vpin_signal.hpp"

#include "dynamic_composite.hpp"
#include "static_composite.hpp"
